FROM ubuntu:jammy

RUN apt-get update

# Install dependencies

# Raw tools
RUN apt-get install -y \
    autoconf \
    python3 \
    python-is-python3 \
    python3-distutils \
    unzip \
    zip \
    systemtap-sdt-dev \
    libxtst-dev \
    libasound2-dev \
    libelf-dev \
    libfontconfig1-dev \
    libx11-dev \
    libxext-dev \
    libxrandr-dev \
    libxrender-dev \
    libxtst-dev \
    libxt-dev \
    wget \
    clang \
    git \
    file \
    make

# JDK 17
RUN apt-get install -y openjdk-17-jdk


WORKDIR /home

COPY . .