#!/bin/bash
set -e

# What is this piece of loop?
# It fixes -DSTUFF='{"stuff"}' where single bracket outside of value lost.
index=0
otherargs=
for i
do
  # Maybe you won't understand this :)
  # As we are running on eval (to fix arguments), we need to escape brackets.
  i=${i//\"/\\\"}

  if [[ $i == -D*={*} ]]; then
    otherargs+="\"$i\" "
  else
    otherargs+="$i "
  fi
done

$(eval $thecc -arch arm64 -isysroot $thesysroot $otherargs)
