#!/bin/bash
set -e

# What is this piece of loop?
# It fixes -DSTUFF='{"stuff"}' where single bracket outside of value lost.
index=0
shouldfix=0
otherargs="-arch arm64 -isysroot $thesysroot "
for i
do

  if [[ $i == -D*={*} ]]; then
    # Maybe you won't understand this :)
    # As we are running on eval (to fix arguments), we need to escape brackets.
    i=${i//\"/\\\"}
    otherargs+="\'$i\' "
    shouldfix=1
  else
    otherargs+="$i "
  fi
done

if [[ $shouldfix -eq 1 ]]; then
  $(eval $thecc $otherargs)
else
  $thecc $otherargs
fi
